name: history_class
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - folium
  - matplotlib
  - Pillow
  - pandas
  - PyPDF2
  - pdf2image
  - pip
  - jupyterlab
  - pip:
    - pytesseract